# Site settings
title: TheFragebogen
email: your-email@TheFragebogen.de
description: "TheFragebogen is a software framework for building questionnaires for the web."
baseurl: "/"
url: "/"

safe: true

# Build settings
markdown: kramdown
kramdown:
  auto_id_stripping: true
  
permalink: pretty
highlighter: rouge
exclude: [raw]
